version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: redis-lock-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-lock-redis
    ports:
      - "6379:6379"

  app1:
    build: .
    container_name: redis-lock-app1
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=test
    depends_on:
      - redis
      - postgres

  app2:
    build: .
    container_name: redis-lock-app2
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=test
    depends_on:
      - redis
      - postgres

  app3:
    build: .
    container_name: redis-lock-app3
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_DATABASE=test
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
